import React from "react";
import Tone from "tone";
import axios from "axios";
import {Redirect} from "react-router-dom";

import SheetMusic from "../components/SheetMusic";
import {EmitPlayButton} from "../components/PlayButton";

// The page where the user sees the comparison between their input and the actual song
class ComparePage extends React.Component {
  /*
  loading: whether the page is still asking for data from the server or not
  redirect_home: whether the page should prepare to redirect to the home page
  redirect_main: whether the page should prepare to redirect to the main page
  actual_song: the note data on the song generated by the site
  corrected_song: the note data on the user input corrected
  */
  state = {
    loading: true,
    redirect_home: false,
    redirect_main: false, // TODO: can be refactored out
    actual_song: [],
    corrected_song: []
  };

  componentDidMount() {
    //Sends in the data to check if the user input is correct
    if (!this.props.hasPost()) {
      this.setState({
        redirect_home: true
      });
    } else {
      axios
        .post("/api/compare", this.props.popPost())
        .then(response => JSON.parse(response.data))
        .then(json => {
          this.setState({
            actual_song: json.actual,
            corrected_song: json.corrected,
            loading: false
          });
          console.log(json);
        })
        .catch(function(error) {
          console.log(error);
        });
    }
  }

  // Returns the amount of notes correct that the user inputted
  getAmtCorrect = () => {
    return this.state.corrected_song.filter(note => note.correct).length;
  };

  // Returns the total number of notes
  getTotal = () => {
    return this.state.actual_song.length;
  };

  // Redirects to main
  handlePlayAgain = () => {
    Tone.Transport.stop();
    this.setState({
      redirect_main: true
    });
  };

  // Redirects home
  handleBackToStart = () => {
    Tone.Transport.stop();
    this.setState({
      redirect_home: true
    });
  };

  getPct = () => {
    return Math.floor((this.getAmtCorrect() / this.getTotal()) * 100);
  };
  render() {
    if (this.state.redirect_home) {
      return <Redirect to="/" />;
    }
    if (this.state.redirect_main) {
      return <Redirect to="/main" />;
    }
    if (this.state.loading) {
      return null;
    }
    return (
      <div className="h-100 row align-items-center">
        <div className="col">
        <div className="d-flex flex-row align-items-center justify-content-between my-2">
          <h3 className="m-0 font-weight-bold">Actual Transcription</h3>
          <EmitPlayButton music={this.state.actual_song} />
        </div>
        <SheetMusic
          keyId={1}
          width={window.innerWidth - 10 * 2}
          height={window.innerHeight / 3}
          notes={this.state.actual_song}
          editable={false}
        />
        <div className="d-flex flex-row align-items-center justify-content-between my-2">
          <h3 className="m-0 font-weight-bold">Your Transcription ({this.getPct()}% correct)</h3>
          <EmitPlayButton music={this.state.corrected_song} />
        </div>
        <SheetMusic
          keyId={2}
          width={window.innerWidth - 10 * 2}
          height={window.innerHeight / 3}
          notes={this.state.corrected_song}
          editable={false}
          comparison={true}
        />
      <div className="d-flex flex-row align-items-center justify-content-center my-2">
        <button className="medium" onClick={this.handleBackToStart}>Quit</button>
        <button className="medium red" onClick={this.handlePlayAgain} >Try again</button>
        </div>
        </div>
      </div>
    );
  }
}

export default ComparePage;
